name: Release Binary

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:
    inputs:
      tag_name:
        description: '发布版本号 (如 v1.0.0-test)'
        required: true
        default: 'manual-test'

permissions:
  contents: write

jobs:
  build-frontend:
    runs-on: ubuntu-latest
    steps:
      - name: 检出代码
        uses: actions/checkout@v4

      - name: 设置 deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x

      - name: 安装依赖
        working-directory: frontend_clean
        run: deno install

      - name: 构建 SvelteKit 静态站点
        working-directory: frontend_clean
        run: deno task build

      - name: 上传前端 artifact
        uses: actions/upload-artifact@v4
        with:
          name: ui-build
          path: frontend_clean/build/

  build-backend:
    needs: build-frontend
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            bin_name: server
            asset_name: qlens-linux-amd64

          - os: windows-latest
            target: x86_64-pc-windows-msvc
            bin_name: server.exe
            asset_name: qlens-windows-amd64.exe

          - os: macos-latest
            target: aarch64-apple-darwin
            bin_name: server
            asset_name: qlens-macos-arm64

    runs-on: ${{ matrix.os }}
    steps:
      - name: 检出代码
        uses: actions/checkout@v4

      - name: 下载已构建的 "ui" 文件夹
        uses: actions/download-artifact@v4
        with:
          name: ui-build
          path: frontend_clean/build

      - name: 设置 Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.target }}

      - name: 下载并配置字体资源
        shell: bash
        run: |
          curl -L -o font.zip https://github.com/subframe7536/maple-font/releases/download/v7.6/MapleMonoNL-NF-CN.zip
          unzip -j -o font.zip "MapleMonoNL-NF-CN-Regular.ttf"
          mv MapleMonoNL-NF-CN-Regular.ttf font.ttf
          rm font.zip

      - name: 构建 Rust 二进制文件
        run: cargo build --release --target ${{ matrix.target }}

      - name: 重命名二进制文件
        shell: bash
        run: |
          cp target/${{ matrix.target }}/release/${{ matrix.bin_name }} ${{ matrix.asset_name }}

      - name: 上传最终二进制文件
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.asset_name }}
          path: ${{ matrix.asset_name }}

  publish-release:
    needs: build-backend
    runs-on: ubuntu-latest
    steps:
      - name: 下载所有已编译的二进制文件
        uses: actions/download-artifact@v4
        with:
          path: dist
          merge-multiple: true

      - name: 创建 GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: dist/qlens-*
          tag_name: ${{ inputs.tag_name || github.ref_name }}
          draft: ${{ github.event_name == 'workflow_dispatch' }}
